* Tuning
** SSD vs HDD
LSM-trees are a good data structure for disk hard drives, because they eliminate random writes. Sequential writes are advantageous on SSDs as well, because of block erase, but naively using an LSM-tree on an SSD is inefficient because the high parallelism of the SSD is not exploited.

SSDs have a multi-channel architecture.

*** Memtables
Increase the limit on the number of immutable memtables. In a multi-channel drive, writing one immutable memtable to disk cannot saturate the channels.
Results show improved throughput until the number of memtables equals the number of channels.

*** Level 0 triggers
- kL0_Compaction_Trigger. Start compaction after this many L0 files are created.
- kL0_SlowdownWritesTrigger. Sleep (1ms) each write after L0 files threshold reacher.
- kL0_StopWritesTrigger. Stop all writes until background compaction completes.

The trigger values should be higher on SSDs than HDDs.

*** Multiple compactions
A multi-channel drive should be able to handle multiple compactions simultaneously without performance degradation. (Is there a guarantee of correctness here?)

** Sources
- https://github.com/EighteenZi/rocksdb_wiki/blob/master/RocksDB-Tuning-Guide.md
- https://github.com/facebook/rocksdb/wiki/Write-Stalls
- "An Efficient Design and Implementation of LSM-Tree based Key-Value Store on Open-Channel SSD"
